server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:childer
    driver-class-name: org.h2.Driver
    username: test
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      format_sql: true