server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:childer
    driver-class-name: org.h2.Driver
    username: test
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      format_sql: true
jwt:
  security:
    key: QmxhY2tKYWNrQmxhY2tQbGF5aW5nQUJsYWNrSmFja1doaWxlUGxheWluZ0JsYWNrSmFja1dpdGhKYWNrQmxhY2s=
    expire: 1800000